version: '2'

services:
  dev:
    image: oinker/oinker_admin
    ports:
      - 8090:80
    volumes:
      - ./src/public:/var/www/html
    environment:
        - API_BASE_URI=http://#/api/v1
        - MAINTENANCE_MODE=0
        - CLIENT_ID=#
        - CLIENT_SECRET=#
        - OAUTH_SCOPE=admin
        - OAUTH_AUTHORIZE_URL=http://#/authorize
        - OAUTH_REDIRECT_URL=http://#/authorize
